api/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Sidekiq::Web, at: "/sidekiq" if ENV["LAGO_SIDEKIQ_WEB"] == "true" && defined? Sidekiq::Web
  mount Karafka::Web::App, at: "/karafka" if ENV["LAGO_KARAFKA_WEB"]
  mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql" if Rails.env.development?
  mount Yabeda::Prometheus::Exporter, at: "/metrics"
  mount ActionCable.server, at: "/cable"

  post "/graphql", to: "graphql#execute"

  # Health Check status
  get "/health", to: "application#health"

  namespace :data_api do
    namespace :v1 do
      resources :charges, only: [] do
        post :forecasted_usage_amount, on: :member
        post :bulk_forecasted_usage_amount, on: :collection
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :activity_logs, param: :activity_id, only: %i[index show]
      resources :api_logs, param: :request_id, only: %i[index show]

      namespace :analytics do
        get :gross_revenue, to: "gross_revenues#index", as: :gross_revenue
        get :invoiced_usage, to: "invoiced_usages#index", as: :invoiced_usage
        get :invoice_collection, to: "invoice_collections#index", as: :invoice_collection
        get :mrr, to: "mrrs#index", as: :mrr
        get :overdue_balance, to: "overdue_balances#index", as: :overdue_balance
      end

      get "analytics/usage", to: "data_api/usages#index", as: :usage

      resources :billing_entities, param: :code, only: %i[index show update create]

      resources :customers, param: :external_id, only: %i[create index show destroy] do
        get :portal_url

        get :current_usage, to: "customers/usage#current"
        get :projected_usage, to: "customers/projected_usage#current"
        get :past_usage, to: "customers/usage#past"

        post :checkout_url

        scope module: :customers do
          resources :applied_coupons, only: %i[index destroy]
          resources :credit_notes, only: %i[index]
          resources :invoices, only: %i[index]
          resources :payments, only: %i[index]
          resources :payment_requests, only: %i[index]
          resources :subscriptions, only: %i[index]
          resources :wallets, only: %i[index]
          resources :payment_methods, only: %i[index destroy] do
            put :set_as_default, on: :member
          end
        end
      end

      resources :subscriptions, only: %i[create update show index], param: :external_id do
        resource :lifetime_usage, only: %i[show update], controller: "subscriptions/lifetime_usages"
        resources :alerts, only: %i[create index update show destroy], param: :code, controller: "subscriptions/alerts"
        resources :entitlements, only: %i[index destroy], param: :code, code: /.*/, controller: "subscriptions/entitlements" do
          resources :privileges, only: %i[destroy], param: :code, code: /.*/, controller: "subscriptions/entitlements/privileges"
        end
        patch :entitlements, to: "subscriptions/entitlements#update"
        resources :fixed_charges, only: %i[index], controller: "subscriptions/fixed_charges"
      end
      delete "/subscriptions/:external_id", to: "subscriptions#terminate", as: :terminate

      resources :add_ons, param: :code, code: /.*/
      resources :billable_metrics, param: :code, code: /.*/ do
        post :evaluate_expression, on: :collection
      end

      resources :features, param: :code, code: /.*/, only: %i[index show create update destroy] do
        scope module: :features do
          resources :privileges, only: %i[destroy], param: :code
        end
      end

      resources :coupons, param: :code, code: /.*/
      resources :credit_notes, only: %i[create update show index] do
        post :download, on: :member
        put :void, on: :member
        post :estimate, on: :collection
      end
      resources :events, only: %i[create show index] do
        post :estimate_fees, on: :collection
        post :estimate_instant_fees, on: :collection
        post :batch_estimate_instant_fees, on: :collection
      end
      resources :applied_coupons, only: %i[create index]
      resources :fees, only: %i[show update index destroy]
      resources :invoices, only: %i[create update show index] do
        post :download, on: :member, action: :download_pdf
        post :download_pdf, on: :member
        post :download_xml, on: :member
        post :void, on: :member
        post :lose_dispute, on: :member
        post :retry, on: :member
        post :retry_payment, on: :member
        post :payment_url, on: :member
        post :preview, on: :collection
        put :refresh, on: :member
        put :finalize, on: :member
        put :sync_salesforce_id, on: :member
      end
      resources :payment_receipts, only: %i[index show]
      resources :payment_requests, only: %i[create index show]
      resources :payments, only: %i[create index show]
      resources :plans, param: :code, code: /.*/ do
        resources :entitlements, only: %i[index show create destroy], param: :code, code: /.*/, controller: "plans/entitlements" do
          resources :privileges, only: %i[destroy], param: :code, code: /.*/, controller: "plans/entitlements/privileges"
        end
        patch :entitlements, to: "plans/entitlements#update"
      end
      resources :taxes, param: :code, code: /.*/
      resources :wallet_transactions, only: %i[create show] do
        post :payment_url, on: :member
      end
      get "/wallets/:id/wallet_transactions", to: "wallet_transactions#index"
      resources :wallets, only: %i[create update show index]
      delete "/wallets/:id", to: "wallets#terminate"
      post "/events/batch", to: "events#batch"

      get "/organizations", to: "organizations#show"
      put "/organizations", to: "organizations#update"
      get "/organizations/grpc_token", to: "organizations#grpc_token"

      resources :webhook_endpoints, only: %i[create index show destroy update]
      resources :webhooks, only: %i[] do
        get :public_key, on: :collection
        get :json_public_key, on: :collection
      end
    end
  end
  resources :webhooks, only: [] do
    post "stripe/:organization_id", to: "webhooks#stripe", on: :collection, as: :stripe

    post "cashfree/:organization_id", to: "webhooks#cashfree", on: :collection, as: :cashfree
    post "flutterwave/:organization_id", to: "webhooks#flutterwave", on: :collection, as: :flutterwave
    post "gocardless/:organization_id", to: "webhooks#gocardless", on: :collection, as: :gocardless
    post "adyen/:organization_id", to: "webhooks#adyen", on: :collection, as: :adyen
    post "moneyhash/:organization_id", to: "webhooks#moneyhash", on: :collection, as: :moneyhash
  end

  namespace :admin do
    resources :memberships, only: %i[create]
    resources :organizations, only: %i[update create]
    resources :invoices do
      post :regenerate, on: :member
    end
  end

  if Rails.env.development?
    namespace :dev_tools do
      get "/invoices/:id", to: "invoices#show"
      get "/payment_receipts/:id", to: "payment_receipts#show"
    end
  end

  match "*unmatched" => "application#not_found",
    :via => %i[get post put delete patch],
    :constraints => lambda { |req|
      req.path.exclude?("rails/active_storage")
    }
end

api/app/models/plan.rb
# frozen_string_literal: true

class Plan < ApplicationRecord
  include PaperTrailTraceable
  include Currencies
  include Discard::Model
  self.discard_column = :deleted_at

  belongs_to :organization
  belongs_to :parent, class_name: "Plan", optional: true

  has_one :minimum_commitment, -> { where(commitment_type: :minimum_commitment) }, class_name: "Commitment"

  has_many :commitments
  has_many :charges, dependent: :destroy
  has_many :billable_metrics, through: :charges
  has_many :fixed_charges, dependent: :destroy
  has_many :add_ons, through: :fixed_charges
  has_many :subscriptions
  has_many :customers, through: :subscriptions
  has_many :children, class_name: "Plan", foreign_key: :parent_id, dependent: :destroy
  has_many :coupon_targets
  has_many :coupons, through: :coupon_targets
  has_many :invoices, through: :subscriptions
  has_many :usage_thresholds

  has_many :applied_taxes, class_name: "Plan::AppliedTax", dependent: :destroy
  has_many :taxes, through: :applied_taxes
  has_many :entitlements, class_name: "Entitlement::Entitlement", dependent: :destroy
  has_many :entitlement_values, through: :entitlements, source: :values, class_name: "Entitlement::EntitlementValue", dependent: :destroy

  has_many :activity_logs,
    -> { order(logged_at: :desc) },
    class_name: "Clickhouse::ActivityLog",
    as: :resource

  INTERVALS = %i[
    weekly
    monthly
    yearly
    quarterly
    semiannual
  ].freeze

  enum :interval, INTERVALS, validate: true

  monetize :amount_cents

  validates :name, :code, presence: true
  validates :amount_currency, inclusion: {in: currency_list}
  validates :pay_in_advance, inclusion: {in: [true, false]}
  validate :validate_code_unique

  default_scope -> { kept }
  scope :parents, -> { where(parent_id: nil) }

  def self.ransackable_attributes(_auth_object = nil)
    %w[name code]
  end

  def pay_in_arrears?
    !pay_in_advance
  end

  def attached_to_subscriptions?
    subscriptions.exists?
  end

  def has_trial?
    trial_period.present? && trial_period.positive?
  end

  def charges_billed_in_monthly_split_intervals?
    bill_charges_monthly? && (yearly? || semiannual?)
  end

  def fixed_charges_billed_in_monthly_split_intervals?
    bill_fixed_charges_monthly? && (yearly? || semiannual?)
  end

  def charges_or_fixed_charges_billed_in_monthly_split_intervals?
    charges_billed_in_monthly_split_intervals? || fixed_charges_billed_in_monthly_split_intervals?
  end

  def invoice_name
    invoice_display_name.presence || name
  end

  # NOTE: Method used to compare plan for upgrade / downgrade on
  #       a same duration basis. It is not intended to be used
  #       directly for billing/invoicing purpose
  def yearly_amount_cents
    return amount_cents if yearly?
    return amount_cents * 12 if monthly?
    return amount_cents * 4 if quarterly?
    return amount_cents * 2 if semiannual?

    amount_cents * 52
  end

  def active_subscriptions_count
    count = subscriptions.active.count
    return count unless children

    count + children.joins(:subscriptions).merge(Subscription.active).select("subscriptions.id").distinct.count
  end

  def customers_count
    count = subscriptions.active.select(:customer_id).distinct.count
    return count unless children

    count + children.joins(:subscriptions).merge(Subscription.active).select(:customer_id).distinct.count
  end

  def draft_invoices_count
    count = subscriptions.joins(:invoices).merge(Invoice.draft).select(:invoice_id).distinct.count
    return count unless children

    count + children.joins(:subscriptions).joins(:invoices).merge(Invoice.draft).select(:invoice_id).distinct.count
  end

  private

  def validate_code_unique
    return unless organization
    return if parent_id?

    plan = organization.plans.parents.where(code:).first
    errors.add(:code, :taken) if plan && plan != self
  end
end

# == Schema Information
#
# Table name: plans
#
#  id                         :uuid             not null, primary key
#  amount_cents               :bigint           not null
#  amount_currency            :string           not null
#  bill_charges_monthly       :boolean
#  bill_fixed_charges_monthly :boolean          default(FALSE)
#  code                       :string           not null
#  deleted_at                 :datetime
#  description                :string
#  interval                   :integer          not null
#  invoice_display_name       :string
#  name                       :string           not null
#  pay_in_advance             :boolean          default(FALSE), not null
#  pending_deletion           :boolean          default(FALSE), not null
#  trial_period               :float
#  created_at                 :datetime         not null
#  updated_at                 :datetime         not null
#  organization_id            :uuid             not null
#  parent_id                  :uuid
#
# Indexes
#
#  index_plans_on_bill_fixed_charges_monthly  (bill_fixed_charges_monthly) WHERE ((deleted_at IS NULL) AND (bill_fixed_charges_monthly IS TRUE))
#  index_plans_on_created_at                  (created_at)
#  index_plans_on_deleted_at                  (deleted_at)
#  index_plans_on_organization_id             (organization_id)
#  index_plans_on_organization_id_and_code    (organization_id,code) UNIQUE WHERE ((deleted_at IS NULL) AND (parent_id IS NULL))
#  index_plans_on_parent_id                   (parent_id)
#
# Foreign Keys
#
#  fk_rails_...  (organization_id => organizations.id)
#  fk_rails_...  (parent_id => plans.id)
#

api/app/controllers/api/v1/credit_notes_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class CreditNotesController < Api::BaseController
      include CreditNoteIndex
      def create
        result = CreditNotes::CreateService.call(
          invoice: current_organization.invoices.visible.find_by(id: input_params[:invoice_id]),
          **input_params
        )

        if result.success?
          render(
            json: ::V1::CreditNoteSerializer.new(
              result.credit_note,
              root_name: "credit_note",
              includes: %i[items applied_taxes]
            )
          )
        else
          render_error_response(result)
        end
      end

      def show
        credit_note = current_organization.credit_notes.finalized.find_by(id: params[:id])
        return not_found_error(resource: "credit_note") unless credit_note

        render(
          json: ::V1::CreditNoteSerializer.new(
            credit_note,
            root_name: "credit_note",
            includes: %i[items applied_taxes error_details]
          )
        )
      end

      def update
        credit_note = current_organization.credit_notes.find_by(id: params[:id])
        return not_found_error(resource: "credit_note") unless credit_note

        result = CreditNotes::UpdateService.new(credit_note:, **update_params).call

        if result.success?
          render(
            json: ::V1::CreditNoteSerializer.new(
              credit_note,
              root_name: "credit_note",
              includes: %i[items applied_taxes]
            )
          )
        else
          render_error_response(result)
        end
      end

      def download
        credit_note = current_organization.credit_notes.finalized.find_by(id: params[:id])
        return not_found_error(resource: "credit_note") unless credit_note

        if credit_note.file.present?
          return render(
            json: ::V1::CreditNoteSerializer.new(
              credit_note,
              root_name: "credit_note"
            )
          )
        end

        CreditNotes::GeneratePdfJob.perform_later(credit_note)

        head(:ok)
      end

      def void
        credit_note = current_organization.credit_notes.find_by(id: params[:id])
        return not_found_error(resource: "credit_note") unless credit_note

        result = CreditNotes::VoidService.new(credit_note:).call

        if result.success?
          render(
            json: ::V1::CreditNoteSerializer.new(
              credit_note,
              root_name: "credit_note",
              includes: %i[items applied_taxes]
            )
          )
        else
          render_error_response(result)
        end
      end

      def index
        permitted_params = params.permit(:external_customer_id)
        external_customer_id = permitted_params[:external_customer_id]

        credit_note_index(external_customer_id:)
      end

      def estimate
        result = CreditNotes::EstimateService.call(
          invoice: current_organization.invoices.visible.find_by(id: estimate_params[:invoice_id]),
          items: estimate_params[:items]
        )

        if result.success?
          render(
            json: ::V1::CreditNotes::EstimateSerializer.new(
              result.credit_note,
              root_name: "estimated_credit_note"
            )
          )
        else
          render_error_response(result)
        end
      end

      private

      def input_params
        @input_params ||= params.require(:credit_note)
          .permit(
            :invoice_id,
            :reason,
            :description,
            :credit_amount_cents,
            :refund_amount_cents,
            items: [
              :fee_id,
              :amount_cents
            ]
          )
      end

      def update_params
        params.require(:credit_note).permit(:refund_status)
      end

      def estimate_params
        @estimate_params ||= params.require(:credit_note)
          .permit(
            :invoice_id,
            items: [
              :fee_id,
              :amount_cents
            ]
          )
      end

      def resource_name
        "credit_note"
      end
    end
  end
end

api/app/controllers/api/v1/customers/credit_notes_controller.rb
# frozen_string_literal: true

module Api
  module V1
    module Customers
      class CreditNotesController < BaseController
        include CreditNoteIndex

        def index
          credit_note_index(external_customer_id: customer.external_id)
        end

        private

        def resource_name
          "credit_note"
        end
      end
    end
  end
end

api/app/views/templates/credit_notes/_details.slim
.credit-note-resume.mb-24.overflow-auto
  table.credit-note-resume-table width="100%"
    tr
      td.body-3 = I18n.t('credit_note.item')
      - unless for_credit_invoice?
        td.body-3 = I18n.t('credit_note.tax_rate')
      td.body-3 = I18n.t('credit_note.amount')

    - if for_credit_invoice?
      tr
        td.body-1 = I18n.t('credit_note.prepaid_credits_for_wallet', wallet_name: invoice.associated_active_wallet&.name)
        td.body-2 width="20%" = MoneyHelper.format(refund_amount)
    - else
      - subscription_ids.each do |subscription_id|
        - if subscription_id.present?
          - if subscription_item(subscription_id).amount.positive?
            tr
              td.body-1 width="60%"
                | #{I18n.t('credit_note.subscription')} - #{Subscription.find_by(id: subscription_id)&.invoice_name}
              td.body-2 width="20%" == TaxHelper.applied_taxes(subscription_item(subscription_id))
              td.body-2 width="20%" = MoneyHelper.format(subscription_item(subscription_id).amount)

          - subscription_fixed_charge_items(subscription_id).each do |item|
            tr
              td.body-1 width="60%" = item.fee.invoice_name + FeeDisplayHelper.grouped_by_display(item.fee)
              td.body-2 width="20%" == TaxHelper.applied_taxes(item)
              td.body-2 width="20%" = MoneyHelper.format(item.amount)

          - subscription_charge_items(subscription_id).where(fees: { true_up_parent_fee: nil }).group_by { |i| i.fee.charge_id }.each do |_charge_id, items|
            - item = items.first
            - if items.all? { |i| i.fee.charge_filter_id? }
              - items.each do |item|
                tr
                  td.body-1 = item.fee.invoice_name + FeeDisplayHelper.grouped_by_display(item.fee) + ' • ' + item.fee.filter_display_name(separator: ' • ')
                  td.body-2 width="20%" == TaxHelper.applied_taxes(item)
                  td.body-2 width="20%" = MoneyHelper.format(item.amount)
              - items.select { |i| i.fee.true_up_fee.present? }.each do |item|
                - if true_up_item = subscription_charge_items(subscription_id).find_by(fee: item.fee.true_up_fee)
                  tr
                    td.body-1 width="60%" = I18n.t('invoice.true_up_metric', metric: true_up_item.fee.invoice_name)
                    td.body-2 width="20%" == TaxHelper.applied_taxes(true_up_item)
                    td.body-2 width="20%" = MoneyHelper.format(true_up_item.amount)
            - else
              tr
                td.body-1 width="60%" = item.fee.invoice_name + FeeDisplayHelper.grouped_by_display(item.fee)
                td.body-2 width="20%" == TaxHelper.applied_taxes(item)
                td.body-2 width="20%" = MoneyHelper.format(item.amount)
              - if item.fee.true_up_fee.present?
                - if true_up_item = subscription_charge_items(subscription_id).find_by(fee: item.fee.true_up_fee)
                  tr
                    td.body-1 width="60%" = I18n.t('invoice.true_up_metric', metric: true_up_item.fee.invoice_name)
                    td.body-2 width="20%" == TaxHelper.applied_taxes(true_up_item)
                    td.body-2 width="20%" = MoneyHelper.format(true_up_item.amount)
        - else
          - add_on_items.each do |item|
            tr
              td.body-1
                - if item.fee.true_up_parent_fee_id?
                  | #{I18n.t('invoice.true_up_metric', metric: item.fee.true_up_parent_fee.invoice_name)}
                - else
                  | #{item.fee.invoice_name}

              td.body-2 width="20%" == TaxHelper.applied_taxes(item)
              td.body-2 width="20%" = MoneyHelper.format(item.amount)

  table.total-table width="100%"
    - if coupons_adjustment_amount_cents.positive?
      tr
        td.body-2
        td.body-2 width="70%" = I18n.t('credit_note.coupon_adjustment')
        td.body-2 width="30%"
          | -#{MoneyHelper.format(coupons_adjustment_amount)}
    - unless for_credit_invoice?
      tr
        td.body-2
        td.body-2 width="70%" = I18n.t('credit_note.sub_total_without_tax')
        td.body-2 width="30%" = MoneyHelper.format(sub_total_excluding_taxes_amount)
    - if applied_taxes.present?
      - applied_taxes.order(tax_rate: :desc).each do |applied_tax|
        tr
          td.body-2
          td.body-2
            = I18n.t('credit_note.tax', name: applied_tax.tax_name, rate: applied_tax.tax_rate, amount: MoneyHelper.format(applied_tax.base_amount))
          td.body-2 = MoneyHelper.format(applied_tax.amount)
    - else
      - unless for_credit_invoice?
        tr
          td.body-2
          td.body-2 = I18n.t('invoice.tax_name_with_details', name: 'Tax', rate: 0)
          td.body-2 = MoneyHelper.format(0.to_money(currency))
    - if credited?
      tr
        td.body-2
        td.body-2 = I18n.t('credit_note.credited_on_customer_balance')
        td.body-2 = MoneyHelper.format(credit_amount)
    - if refunded?
      tr
        td.body-2
        td.body-2 = I18n.t('credit_note.refunded')
        td.body-2 = MoneyHelper.format(refund_amount)
    tr
      td.body-2
      td.body-1 = I18n.t('credit_note.total')
      td.body-1 = MoneyHelper.format(total_amount)

api/app/views/templates/credit_notes/_eu_tax_management.slim
- if billing_entity.eu_tax_management.present?
  - if applied_taxes.present?
    - applied_tax_codes = applied_taxes.pluck(:tax_code)
    p.body-3.mb-24
      - if applied_tax_codes.include?('lago_eu_tax_exempt')
        - if billing_entity.country == 'FR'
          = I18n.t('invoice.taxes.fr_tax_exempt')
        - else
          = I18n.t('invoice.taxes.tax_exempt')
      - if applied_tax_codes.include?('lago_eu_reverse_charge')
        = I18n.t('invoice.taxes.reverse_charge')

api/app/views/templates/credit_notes/_powered_by_logo.slim
- unless organization.remove_branding_watermark_enabled?
  .powered-by
    span.body-2
      | #{I18n.t('credit_note.powered_by')} &nbsp;
    img src="#{::SlimHelper::PDF_LOGO_FILENAME}" alt="Lago Logo"

api/app/views/templates/credit_notes/_styles.slim
css:
  @font-face {
    font-family: 'Inter';
    font-style:  normal;
    font-weight: 100;
    font-display: swap;
    src: local("Inter-Thin");
  }
  @font-face {
    font-family: 'Inter';
    font-style:  italic;
    font-weight: 100;
    font-display: swap;
    src: local("Inter-ThinItalic");
  }

  @font-face {
    font-family: 'Inter';
    font-style:  normal;
    font-weight: 200;
    font-display: swap;
    src: local("Inter-ExtraLight");
  }
  @font-face {
    font-family: 'Inter';
    font-style:  italic;
    font-weight: 200;
    font-display: swap;
    src: local("Inter-ExtraLightItalic");
  }

  @font-face {
    font-family: 'Inter';
    font-style:  normal;
    font-weight: 300;
    font-display: swap;
    src: local("Inter-Light");
  }
  @font-face {
    font-family: 'Inter';
    font-style:  italic;
    font-weight: 300;
    font-display: swap;
    src: local("Inter-LightItalic");
  }

  @font-face {
    font-family: 'Inter';
    font-style:  normal;
    font-weight: 400;
    font-display: swap;
    src: local("Inter-Regular");
  }
  @font-face {
    font-family: 'Inter';
    font-style:  italic;
    font-weight: 400;
    font-display: swap;
    src: local("Inter-Italic");
  }

  @font-face {
    font-family: 'Inter';
    font-style:  normal;
    font-weight: 500;
    font-display: swap;
    src: local("Inter-Medium");
  }
  @font-face {
    font-family: 'Inter';
    font-style:  italic;
    font-weight: 500;
    font-display: swap;
    src: local("Inter-MediumItalic");
  }

  @font-face {
    font-family: 'Inter';
    font-style:  normal;
    font-weight: 600;
    font-display: swap;
    src: local("Inter-SemiBold");
  }
  @font-face {
    font-family: 'Inter';
    font-style:  italic;
    font-weight: 600;
    font-display: swap;
    src: local("Inter-SemiBoldItalic");
  }

  @font-face {
    font-family: 'Inter';
    font-style:  normal;
    font-weight: 700;
    font-display: swap;
    src: local("Inter-Bold");
  }
  @font-face {
    font-family: 'Inter';
    font-style:  italic;
    font-weight: 700;
    font-display: swap;
    src: local("Inter-BoldItalic");
  }

  @font-face {
    font-family: 'Inter';
    font-style:  normal;
    font-weight: 800;
    font-display: swap;
    src: local("Inter-ExtraBold");
  }
  @font-face {
    font-family: 'Inter';
    font-style:  italic;
    font-weight: 800;
    font-display: swap;
    src: local("Inter-ExtraBoldItalic");
  }

  @font-face {
    font-family: 'Inter';
    font-style:  normal;
    font-weight: 900;
    font-display: swap;
    src: local("Inter-Black");
  }
  @font-face {
    font-family: 'Inter';
    font-style:  italic;
    font-weight: 900;
    font-display: swap;
    src: local("Inter-BlackItalic");
  }


  /* ----------------------- variable ----------------------- */

  @font-face {
    font-family: 'Inter var';
    font-style: normal;
    font-weight: 100 900;
    font-display: swap;
    src: local('Inter-roman') format('woff2');
    font-named-instance: 'Regular';
  }

  @font-face {
    font-family: 'Inter var';
    font-style: italic;
    font-weight: 100 900;
    font-display: swap;
    src: local('Inter-italic') format('woff2');
    font-named-instance: 'Italic';
  }
  h1, h2, p { margin: 0; padding: 0; }
  html { font-family: Inter, sans-serif; }
  h1 { color: #19212e; font-weight: 700; font-size: 24px; line-height: 32px; }
  h2 {
    color: #19212e;
    font-weight: 700;
    font-size: 18px;
    line-height: 24px;
  }
  .body-1 {
    color: #19212e;
    font-weight: 600;
    font-size: 10px;
    line-height: 16px;
  }
  .body-2 {
    color: #19212e;
    font-weight: 400;
    font-size: 10px;
    line-height: 16px;
  }
  .body-3 {
    color: #66758f;
    font-weight: 400;
    font-size: 9px;
    line-height: 16px;
  }

  .mb-8 {
    margin-bottom: 8px;
  }
  .mb-24 {
    margin-bottom: 24px;
  }

  .overflow-auto {
    overflow: auto;
  }
  tr {
    break-inside: avoid;
  }

  .credit-note-title {
    display: inline;
  }
  .header-logo {
    float: right;
    max-height: 32px;
  }

  .credit-note-information-column {
    float: left;
    width: 50%;
  }
  .credit-note-information-table tr td:first-child {
    padding: 0 16px 0 0;
  }
  .credit-note-information-table tr td:last-child {
    width: 55%;
  }
  .credit-note-information-table, tr td{
    text-wrap: normal;
    word-wrap: break-word;
    vertical-align: top;
  }
  .credit-note-information-table {
    border-collapse: collapse;
    table-layout: fixed;
    width: 100%;
  }

  .billing-information-column {
    float: left;
    width: 50%;
  }

  .credit-note-resume-table tr {
    border-bottom: 1px solid #D9DEE7;
  }
  .credit-note-resume-table tr td {
    padding-top: 8px;
    padding-bottom: 8px;
  }
  .credit-note-resume-table tr td:last-child {
    text-align: right;
  }
  .credit-note-resume table {
    border-collapse: collapse;
  }

  .credit-note-resume .total-table tr td {
    padding-top: 8px;
    padding-bottom: 8px;
    text-align: right;
  }
  .credit-note-resume .total-table td:first-child {
    width: 50%;
  }
  .credit-note-resume .total-table tr:not(:last-child) td:nth-child(2) {
    border-bottom: 1px solid #D9DEE7;
    text-align: left;
    width: 35%;
  }
  .credit-note-resume .total-table tr:not(:last-child) td:nth-child(3) {
    border-bottom: 1px solid #D9DEE7;
    text-align: right;
    width: 35%;
  }
  .credit-note-resume .total-table tr:last-child td:nth-child(2) {
    text-align: left;
    width: 35%;
  }
  .credit-note-resume .total-table tr:last-child td:nth-child(3) {
    text-align: right;
    width: 15%;
  }

  .powered-by {
    width: 100%;
    text-align: right;
  }
  .powered-by span {
    color: #8c95a6;
  }
  .powered-by img {
    width: 37px;
    height: 11px;
    vertical-align: middle;
    margin-top: 2px;
  }